language: node_js
sudo: false
node_js:
  - 8
install:
  - yarn
script:
  - yarn tslint
  - yarn build
  - yarn test
  - yarn build:doc

cache: yarn

deploy:
  provider: pages
  local_dir: doc
  skip_cleanup: true
  github_token: $GITHUB_KEY # Set in travis-ci.org dashboard
  on:
    branch: master
