trigger:
- master
- dev

jobs:
  - job: "MacOS"
    pool:
      vmImage: 'macos-10.13'
    steps:
      - template: 'build/build-test-freeze.yml'
        parameters:
          platform: "macos-x64"
  - job: "Linux"
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: 'build/build-test-freeze.yml'
        parameters:
          platform: "linux-x64"
  - job: Deploy
    dependsOn:
      - MacOS
      - Linux
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/dev')))
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: DownloadPipelineArtifact@1
        displayName: Download Artifacts from other jobs
        inputs:
          buildType: 'current'
      - task: GitHubRelease@0
        displayName: Upload CLI Prereleases to Github
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
        inputs:
          gitHubConnection: "release"
          repositoryName: "buttplugio/buttplug-js"
          action: "edit"
          tagSource: "manual"
          tag: "420.69.666"
          title: "Buttplug JS CLI Prerelease"
          assets: "$(System.ArtifactsDirectory)/**/*.zip"
          isPreRelease: true
      - task: GitHubRelease@0
        displayName: Upload CLI releases to Github
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          gitHubConnection: "release"
          repositoryName: "buttplugio/buttplug-js"
          action: "create"
          tagSource: "auto"
          title: "Buttplug JS CLI Release"
          assets: "$(System.ArtifactsDirectory)/**/*.zip"
          isPreRelease: false
