language: node_js
sudo: false
node_js:
  - 9
install:
  - yarn
script:
  - yarn tslint
  - yarn build:main
  - yarn build:doc
  - yarn test

cache: yarn

deploy:
  provider: pages
  local_dir: doc
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
